---
- name: "Transfer Files"
  copy:
    src: "/home/ansible/postgresql_packages/{{ item }}"
    dest: /root/postgresql_packages/
  loop: "{{ postgresql_packages }}"
  register: copied

- name: "Install Local RPM postgresql12-libs"
  yum:
    name: /root/postgresql_packages/postgresql12-libs-12.5-1PGDG.rhel8.x86_64.rpm
    state: present

- name: "Install Local RPM postgresql12"
  yum:
    name: /root/postgresql_packages/postgresql12-12.5-1PGDG.rhel8.x86_64.rpm
    state: present

- name: "Install Local RPM postgresql12-server"
  yum:
    name: /root/postgresql_packages/postgresql12-server-12.5-1PGDG.rhel8.x86_64.rpm
    state: present
