---
- name: Import Postgresql-12 GPG key from a url
  rpm_key:
    state: present
    key: https://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-12

- name: "Install Local RPM postgresql12-libs"
  yum:
    name: "files/{{  postgresql_packages  }}"
    state: present